name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      azure_cred: ${{ secrets.AZURE_CREDENTIALS }}  
    steps:
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@master
        with:
          ref: ${{github.ref}}
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az account show

#       - name: secretBash	
#         run: |
#           $azure_cred = $env:azure_cred
#           sed -i -e 's/TESTSERVICENAME/'$azure_cred'/g' .cloud/.azure/test/test_deploy.json
#           jq . .cloud/.azure/test/test_deploy.json
