name: Integration Test
on: [push , pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@master
        with:
          ref: ${{github.ref}}

      # # connect to above created workspace
      # - name: Connect Workspace
      #   id: ws_connect
      #   uses: ./
      #   with:
      #     azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
      #     parameters_file: "test/workspace.json"
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            chmod +x $GITHUB_WORKSPACE/cleanup.sh ${{secrets.AZURE_CREDENTIALS}}