name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@master
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Self test
        id: selftest
        uses: ashishonce/amlworkspace_2@master
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
        continue-on-error: true
