name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      azure_cred: ${{ secrets.AZURE_CREDENTIALS }}  
    steps:
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@master
        with:
          ref: ${{github.ref}}

      - name: secretBash	
        run: |
          $azure_cred = $env:azure_cred
          sed -i -e 's/TESTSERVICENAME/'$azure_cred'/g' .cloud/.azure/test/test_deploy.json
          jq . .cloud/.azure/test/test_deploy.json
