name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@master
        with:
          ref: ${{github.ref}}

      - name: secretBash	
        run: |
          sed -i -e 's/TESTSERVICENAME/'$1'/g' .cloud/.azure/test/test_deploy.json
          jq . .cloud/.azure/test/test_deploy.json