name: Integration Test
on: [push , pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Self test
        id: selftest
        uses: ./
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
        continue-on-error: true
